name = "line-app"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "db"
database_name = "line-app"
database_id = "70384081-5bbd-4920-8ee1-df8ccdc43616"
preview_database_id = "08785bf0-7909-46a6-85d5-ee405e24b829"
migrations_dir = ".wrangler/migrations"